num_handymen: 1
max_tool_sections: 3
max_vertices_per_tool_section: 9
max_environment_objects: 5
max_vertices_per_environment_object: 9
max_velocity: 80
thrust_penalty: -0.5
max_acceleration: 1.0


tool_touching_dynamic_object_reward: 10
tool_separating_from_dynamic_object_reward: 4
tool_touching_static_object_reward: -3
tool_separating_from_static_object_reward: 1

tool_following_support_vector_reward: 10
agent_selfishness: 0.5
goal_reward: 1000.0


tools:
  hammer:
    grip-point:
      x: 15
      y: 0
    scale: 3
    sections:
      - head:
          color:
            red: 60
            green: 60
            blue: 60
          weight: 200000000
          friction: 0.5
          scale: 1
          layer: 1
          points:
            - point1:
                x: 0
                y: 30
            - point2:
                x: 30
                y: 30
            - point3:
                x: 30
                y: 50
            - point4:
                x: 0
                y: 50
      - handle:
          color:
            red: 165
            green: 151
            blue: 59
          weight: 6
          friction: 0.4
          scale: 1
          layer: 2
          points:
            - point1:
                x: 13
                y: 0
            - point2:
                x: 17
                y: 0
            - point3:
                x: 17
                y: 30
            - point4:
                x: 13
                y: 30
  stick:
    grip-point:
      x: 5
      y: 0
    scale: 2
    sections:
      - body:
          color:
            red: 165
            green: 151
            blue: 59
          weight: 8
          friction: 0.44
          scale: 1
          layer: 1
          points:
            - point1:
                x: 0
                y: 0
            - point2:
                x: 10
                y: 0
            - point3:
                x: 10
                y: 100
            - point4:
                x: 0
                y: 100
  crowbar:
    grip-point:
      x: 4
      y: 100
    scale: 2
    sections:
      - shaft:
          color:
            red: 60
            green: 60
            blue: 60
          weight: 8
          friction: 0.2
          scale: 1
          layer: 1
          points:
            - point1:
                x: 15
                y: 0
            - point2:
                x: 15
                y: 8
            - point3:
                x: 8
                y: 20
            - point4:
                x: 8
                y: 100
            - point5:
                x: 0
                y: 100
            - point6:
                x: 0
                y: 20
      - lever:
          color:
            red: 255
            green: 60
            blue: 60
          weight: 20
          friction: 1000000000
          scale: 1
          layer: 2
          points:
            - point1:
                x: 15
                y: 0
            - point2:
                x: 30
                y: 23
            - point3:
                x: 15
                y: 8
  pickaxe:
    grip-point:
      x: 30
      y: 0
    scale: 3
    sections:
      - pick-and-chisel:
          color:
            red: 60
            green: 60
            blue: 60
          weight: 6
          friction: 0.4
          scale: 1
          layer: 1
          points:
            - point1:
                x: 0
                y: 45
            - point2:
                x: 60
                y: 45
            - point3:
                x: 34
                y: 55
            - point4:
                x: 26
                y: 55
      - handle:
          color:
            red: 165
            green: 151
            blue: 59
          weight: 15
          friction: 0.1
          scale: 1
          layer: 2
          points:
            - point1:
                x: 26
                y: 0
            - point2:
                x: 34
                y: 0
            - point3:
                x: 34
                y: 45
            - point4:
                x: 26
                y: 45



goals:
  open-the-chest:
    environment-objects:
      - chest-base:
          type: static
          shape: polygon
          points:
            - point1:
                x: 20
                y: 0
            - point2:
                x: 120
                y: 0
            - point3:
                x: 140
                y: 50
            - point4:
                x: 0
                y: 50
      - chest-top:
          type: dynamic
          shape: polygon
          weight: 5000
          moment: 50000000 # This needs to be very high for more stable simulations
          points:
            - point1:
                x: 0
                y: 61
            - point2:
                x: 140
                y: 61
            - point3:
                x: 120
                y: 80
            - point4:
                x: 20
                y: 80
    hinges:
      - hinge1:
          - chest-base:
              point:
                x: 0
                y: 50
          - chest-top:
              point:
                x: 0
                y: 61
    accomplishment-criteria:
      object: chest-top
      touches:
        x: -140
        y: 30
  kick-the-ball:
    environment-objects:
      - impediment:
          type: static
          shape: polygon
          points:
            - point1:
                x: 400
                y: 1200
            - point2:
                x: 400
                y: 100
            - point3:
                x: 800
                y: 260
            - point4:
                x: 800
                y: 1200
      - ramp:
          type: static
          shape: polygon
          points:
            - point1:
                x: 400
                y: 0
            - point2:
                x: 800
                y: 0
            - point3:
                x: 800
                y: 140
      - ball:
          type: dynamic
          shape: circle
          radius: 24.0
          weight: 80
          moment: 10000000 # This needs to be very high for more stable simulations
    accomplishment-criteria:
      object: ball
      touches:
        x: 1186
        y: 10
  hit-the-nail:
    environment-objects:
      - wall1:
          type: static
          shape: polygon
          friction: 0.3
          points:
            - point1:
                x: 200
                y: 1200
            - point2:
                x: 200
                y: 700
            - point3:
                x: 240
                y: 700
            - point4:
                x: 240
                y: 1200
      - wall2:
          type: static
          shape: polygon
          friction: 0.3
          points:
            - point1:
                x: 200
                y: 600
            - point2:
                x: 200
                y: 0
            - point3:
                x: 240
                y: 0
            - point4:
                x: 240
                y: 600
      - nail:
          type: dynamic
          shape: polygon
          moment: 100000000 # This needs to be very high for more stable simulations
          weight: 100
          friction: 1000000000
          points:
            - point1:
                x: 0
                y: 580
            - point2:
                x: 0
                y: 720
            - point3:
                x: 10
                y: 680
            - point4:
                x: 380
                y: 680
            - point5:
                x: 400
                y: 650
            - point6:
                x: 380
                y: 620
            - point7:
                x: 10
                y: 620
    accomplishment-criteria:
      object: nail
      touches:
        x: 560
        y: 650
      support-vector-initial-perpendicular-pull: 0 # Obtain this from hinge knowledge

offsets:
  open-the-chest:
    initial_tool_position: (WINDOW_SIZE_X/2,WINDOW_SIZE_Y/2)
    initial_goal_position: (2*WINDOW_SIZE_X/3,WINDOW_SIZE_Y)
  kick-the-ball:
    initial_tool_position: (7*WINDOW_SIZE_X/8,3*WINDOW_SIZE_Y/8)
    initial_goal_position: (WINDOW_SIZE_X,WINDOW_SIZE_Y)
  hit-the-nail:
    initial_tool_position: (7*WINDOW_SIZE_X/8,7*WINDOW_SIZE_Y/8)
    initial_goal_position: (2*WINDOW_SIZE_X/3,WINDOW_SIZE_Y)
