tools:
  hammer:
    grip-point:
      x: 15
      y: 0
    scale: 3
    sections:
      - head:
          color:
            red: 60
            green: 60
            blue: 60
          weight: 20
          friction: 0.2
          scale: 1
          layer: 1
          points:
            - point1:
                x: 0
                y: 30
            - point2:
                x: 30
                y: 30
            - point3:
                x: 30
                y: 50
            - point4:
                x: 0
                y: 50
      - handle:
          color:
            red: 165
            green: 151
            blue: 59
          weight: 6
          friction: 0.4
          scale: 1
          layer: 2
          points:
            - point1:
                x: 13
                y: 0
            - point2:
                x: 17
                y: 0
            - point3:
                x: 17
                y: 30
            - point4:
                x: 13
                y: 30
  stick:
    grip-point:
      x: 5
      y: 0
    scale: 2
    sections:
      - body:
          color:
            red: 165
            green: 151
            blue: 59
          weight: 8
          friction: 0.44
          scale: 1
          layer: 1
          points:
            - point1:
                x: 0
                y: 0
            - point2:
                x: 10
                y: 0
            - point3:
                x: 10
                y: 100
            - point4:
                x: 0
                y: 100
  crowbar:
    grip-point:
      x: 4
      y: 100
    scale: 2
    sections:
      - shaft:
          color:
            red: 60
            green: 60
            blue: 60
          weight: 8
          friction: 0.2
          scale: 1
          layer: 1
          points:
            - point1:
                x: 15
                y: 0
            - point2:
                x: 15
                y: 8
            - point3:
                x: 8
                y: 20
            - point4:
                x: 8
                y: 100
            - point5:
                x: 0
                y: 100
            - point6:
                x: 0
                y: 20
      - lever:
          color:
            red: 255
            green: 60
            blue: 60
          weight: 4
          friction: 0.9
          scale: 1
          layer: 2
          points:
            - point1:
                x: 15
                y: 0
            - point2:
                x: 30
                y: 23
            - point3:
                x: 15
                y: 8
  pickaxe:
    grip-point:
      x: 30
      y: 0
    scale: 3
    sections:
      - pick-and-chisel:
          color:
            red: 60
            green: 60
            blue: 60
          weight: 6
          friction: 0.4
          scale: 1
          layer: 1
          points:
            - point1:
                x: 0
                y: 45
            - point2:
                x: 60
                y: 45
            - point3:
                x: 34
                y: 55
            - point4:
                x: 26
                y: 55
      - handle:
          color:
            red: 165
            green: 151
            blue: 59
          weight: 15
          friction: 0.1
          scale: 1
          layer: 2
          points:
            - point1:
                x: 26
                y: 0
            - point2:
                x: 34
                y: 0
            - point3:
                x: 34
                y: 45
            - point4:
                x: 26
                y: 45
goals:
  open-the-chest:
    environment-objects:
      - chest-base:
          type: static
          shape: polygon
          points:
            - point1:
                x: 20
                y: 0
            - point2:
                x: 120
                y: 0
            - point3:
                x: 140
                y: 50
            - point4:
                x: 0
                y: 50
      - chest-top:
          type: dynamic
          shape: polygon
          weight: 80
          points:
            - point1:
                x: 0
                y: 61
            - point2:
                x: 140
                y: 61
            - point3:
                x: 120
                y: 80
            - point4:
                x: 20
                y: 80
    accomplishment-criteria:
      object: chest-top
      touches:
        x: 
        y: 
  kick-the-ball:
    environment-objects:
      - impediment:
          type: static
          shape: polygon
          points:
            - point1:
                x: 
                y: 
            - point2:
                x: 
                y: 
            - point3:
                x: 
                y: 
            - point4:
                x: 
                y: 
      - ramp:
          type: static
          shape: polygon
          points:
            - point1:
                x: 
                y: 
            - point2:
                x: 
                y: 
            - point3:
                x: 
                y: 
            - point4:
                x: 
                y: 
      - ball:
          type: dynamic
          shape: circle
          radius: 15.0
          weight: 80
    accomplishment-criteria:
      object: ball
      touches:
        x: 
        y: 
  hit-the-nail:
    environment-objects:
      - wall1:
          type: static
          shape: polygon
          points:
            - point1:
                x: 
                y: 
            - point2:
                x: 
                y: 
            - point3:
                x: 
                y: 
            - point4:
                x: 
                y: 
      - wall2:
          type: static
          shape: polygon
          points:
            - point1:
                x: 
                y: 
            - point2:
                x: 
                y: 
            - point3:
                x: 
                y: 
            - point4:
                x: 
                y: 
      - nail:
          type: dynamic
          shape: polygon
          weight: 20
          points:
            - point1:
                x: 
                y: 
            - point2:
                x: 
                y: 
            - point3:
                x: 
                y: 
            - point4:
                x: 
                y: 
            - point5:
                x: 
                y: 
    accomplishment-criteria:
      object: nail
      touches:
        x: 
        y: 